name: hello-jerboa
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run jest
        run: make jest
      - name: run jest --coverage
        run: make coverage
